apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adminUser.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: "{{ .Values.adminUser.name }}"
type: kubernetes.io/service-account-token
